[project]
name = "ai-drive-safe"

[deploy]
branch = "main"
command = "npm install && npm start"

[environment]
PORT = "3000"
FIREBASE_PROJECT_ID = "your_project_id"
FIREBASE_CLIENT_EMAIL = "your_service_account_email"
FIREBASE_PRIVATE_KEY = "your_private_key"
